import { NextResponse } from "next/server";

// Served at /firebase-messaging-sw.js. A dynamic route (not a static public/ file)
// so the public Firebase config is injected server-side from NEXT_PUBLIC_* env —
// single source of truth, and no `?query` string that would fork the service
// worker's identity and cause re-registration churn.
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// Matches the installed firebase npm major; gstatic hosts the compat builds.
const FIREBASE_SDK = "10.14.0";

export function GET() {
  const config = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  };

  const body = `// Auto-generated by /firebase-messaging-sw.js — do not edit by hand.
importScripts("https://www.gstatic.com/firebasejs/${FIREBASE_SDK}/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/${FIREBASE_SDK}/firebase-messaging-compat.js");

firebase.initializeApp(${JSON.stringify(config)});

// Initializing messaging in the SW lets the FCM SDK auto-display background
// "notification" messages (what the reminder cron sends). No custom handler needed.
const messaging = firebase.messaging();

// Deep-link to the page in the message's fcmOptions.link / data.route on click.
// No-op fetch listener: required for Chrome's PWA installability heuristic.
// Without a fetch handler, beforeinstallprompt never fires. This listener
// intentionally does NOT intercept the network — all requests pass through normally.
self.addEventListener("fetch", () => {});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const url =
    (event.notification.data && (event.notification.data.FCM_MSG?.data?.route)) ||
    "/my-appointments";
  event.waitUntil(
    clients.matchAll({ type: "window", includeUncontrolled: true }).then((wins) => {
      for (const w of wins) {
        if ("focus" in w) return w.focus();
      }
      if (clients.openWindow) return clients.openWindow(url);
    })
  );
});
`;

  return new NextResponse(body, {
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      "Service-Worker-Allowed": "/",
      "Cache-Control": "public, max-age=0, must-revalidate",
    },
  });
}
